-- Git-only draft metadata seed. Do not apply to hosted or local Supabase
-- in Step 49E. Does not upload Storage objects, publish rows, or insert NCSP.
--
-- Ten owner-controlled previously published works. PDFs are not in this
-- migration. byte_size stays NULL until the exact binary is measured at
-- ingest. All rows remain draft and non-public.
--
-- Deterministic UUIDs. Plain INSERT so an existing UUID or slug fails
-- rather than overwrite.

-- ---------------------------------------------------------------------------
-- Draft media metadata (no objects)
-- ---------------------------------------------------------------------------

INSERT INTO public.media_assets (
  id,
  bucket_path,
  kind,
  purpose,
  title,
  alt_text,
  caption,
  credit,
  year_label,
  mime_type,
  byte_size,
  sort_order,
  is_public,
  status
) VALUES
  (
    '34d3775c-4fa8-47d7-bc35-2c995fc1be61',
    'publication/34d3775c-4fa8-47d7-bc35-2c995fc1be61/privacy-preserving-machine-learning-global-healthcare-ai.pdf',
    'document',
    'publication',
    'Privacy-Preserving Machine Learning in Global Healthcare AI: Breaking the Clinical Validation Bottleneck Without Breaking the Law',
    NULL,
    NULL,
    NULL,
    '2026',
    'application/pdf',
    NULL,
    10,
    false,
    'draft'
  ),
  (
    '3de3cd93-c729-47e9-8096-99e7974a7d5e',
    'publication/3de3cd93-c729-47e9-8096-99e7974a7d5e/egov-ph-architectural-fragility-bcdr.pdf',
    'document',
    'publication',
    'Architectural Fragility and the Illusion of Cost-Savings: A Critical Analysis of the eGov PH Super App Outage and the Imperative for Enterprise-Grade BC/DR',
    NULL,
    NULL,
    NULL,
    '2026',
    'application/pdf',
    NULL,
    20,
    false,
    'draft'
  ),
  (
    'bb275243-05d5-48af-8113-ee9536ac7429',
    'publication/bb275243-05d5-48af-8113-ee9536ac7429/generative-ai-privacy-compliance-documentation.pdf',
    'document',
    'publication',
    'Leveraging Generative Artificial Intelligence for Privacy Compliance Documentation: A Governance Oriented Approach for the European Union, the Philippines, and the APEC Region',
    NULL,
    NULL,
    NULL,
    '2025',
    'application/pdf',
    NULL,
    30,
    false,
    'draft'
  ),
  (
    'b31d3cc2-111f-4f0d-bd56-d19666c0dade',
    'publication/b31d3cc2-111f-4f0d-bd56-d19666c0dade/contain-the-rumor-protect-the-people.pdf',
    'document',
    'publication',
    'Contain the Rumor, Protect the People',
    NULL,
    NULL,
    NULL,
    '2025',
    'application/pdf',
    NULL,
    40,
    false,
    'draft'
  ),
  (
    '1598966c-b991-4f31-8828-f9e2d4664bc6',
    'publication/1598966c-b991-4f31-8828-f9e2d4664bc6/data-breach-to-boardroom-cyber-governance.pdf',
    'document',
    'publication',
    'From Data Breach to Boardroom: Why Cybersecurity Is Now Corporate Governance',
    NULL,
    NULL,
    NULL,
    '2025',
    'application/pdf',
    NULL,
    50,
    false,
    'draft'
  ),
  (
    'ba78a7f8-834d-4e85-a63f-78de5c5af0a1',
    'publication/ba78a7f8-834d-4e85-a63f-78de5c5af0a1/orb-to-oversight-world-app-privacy.pdf',
    'document',
    'publication',
    'From Orb to Oversight: Why the NPC Paused World App',
    NULL,
    NULL,
    NULL,
    '2025',
    'application/pdf',
    NULL,
    60,
    false,
    'draft'
  ),
  (
    '52e8ba31-0122-4a09-b09e-e5fb16d102f7',
    'publication/52e8ba31-0122-4a09-b09e-e5fb16d102f7/you-are-easier-to-hack-than-everything.pdf',
    'document',
    'publication',
    'You Are Easier to Hack Than Everything',
    NULL,
    NULL,
    NULL,
    '2025',
    'application/pdf',
    NULL,
    70,
    false,
    'draft'
  ),
  (
    '9980ca4b-c0ff-45b9-bfb3-283ffdedcf7d',
    'publication/9980ca4b-c0ff-45b9-bfb3-283ffdedcf7d/before-blocks-build-the-bedrock.pdf',
    'document',
    'publication',
    'Before Blocks, Build the Bedrock: Why Blockchain Shouldn''t Lead Philippine Budget Reform—Yet',
    NULL,
    NULL,
    NULL,
    '2025',
    'application/pdf',
    NULL,
    80,
    false,
    'draft'
  ),
  (
    '880703b6-29cb-440a-b60e-8568a76b0a71',
    'publication/880703b6-29cb-440a-b60e-8568a76b0a71/price-of-ubiquity-gcash-critical-infrastructure.pdf',
    'document',
    'publication',
    'The Price of Ubiquity: GCash Is Now Critical Infrastructure',
    NULL,
    NULL,
    NULL,
    '2025',
    'application/pdf',
    NULL,
    90,
    false,
    'draft'
  ),
  (
    '8af86f88-8595-4812-8177-47ca30778300',
    'publication/8af86f88-8595-4812-8177-47ca30778300/philippine-elections-2025-data-privacy.pdf',
    'document',
    'publication',
    'Philippine Elections 2025: The Alarming Rise of Unsecured Personal Data Processing',
    NULL,
    NULL,
    NULL,
    '2025',
    'application/pdf',
    NULL,
    100,
    false,
    'draft'
  );

-- ---------------------------------------------------------------------------
-- Draft publication metadata (linked to draft media; no PDF objects)
-- ---------------------------------------------------------------------------

INSERT INTO public.publications (
  id,
  slug,
  title,
  publisher,
  published_on,
  year_label,
  abstract,
  external_url,
  track,
  status,
  sort_order,
  document_kind,
  rights_status,
  author,
  media_id
) VALUES
  (
    '6aff00bd-be4c-43cd-9dcf-bc649e919b7f',
    'privacy-preserving-machine-learning-global-healthcare-ai',
    'Privacy-Preserving Machine Learning in Global Healthcare AI: Breaking the Clinical Validation Bottleneck Without Breaking the Law',
    'Independent professional publication',
    NULL,
    '2026',
    'A governance and architecture white paper examining how Federated Learning, Differential Privacy, and Fully Homomorphic Encryption can support clinical AI validation while reducing unnecessary movement of regulated health data. The paper connects privacy engineering, cybersecurity, clinical evidence, patient agency, infrastructure equity, and audit-ready governance.',
    NULL,
    'all',
    'draft',
    10,
    'white_paper',
    'host_pdf',
    NULL,
    '34d3775c-4fa8-47d7-bc35-2c995fc1be61'
  ),
  (
    '93bc6513-f2e8-436c-9639-0eb59288aca7',
    'egov-ph-architectural-fragility-bcdr',
    'Architectural Fragility and the Illusion of Cost-Savings: A Critical Analysis of the eGov PH Super App Outage and the Imperative for Enterprise-Grade BC/DR',
    'Independent professional publication',
    NULL,
    '2026',
    'A resilience-focused analysis of the eGov PH Super App outage examining cloud capacity, availability, interoperability, identity governance, data protection, sovereign continuity, and business continuity and disaster recovery for national-scale digital services.',
    NULL,
    'cybersecurity_grc',
    'draft',
    20,
    'white_paper',
    'host_pdf',
    NULL,
    '3de3cd93-c729-47e9-8096-99e7974a7d5e'
  ),
  (
    '1908141e-4455-441d-81bd-d2c801ec5f5b',
    'generative-ai-privacy-compliance-documentation',
    'Leveraging Generative Artificial Intelligence for Privacy Compliance Documentation: A Governance Oriented Approach for the European Union, the Philippines, and the APEC Region',
    'Independent professional publication',
    NULL,
    '2025',
    'A governance-oriented white paper examining the use of Generative AI, Retrieval-Augmented Generation, and structured prompting to support privacy compliance documentation across European, Philippine, and Asia-Pacific regulatory environments.',
    NULL,
    'privacy_ai',
    'draft',
    30,
    'white_paper',
    'host_pdf',
    NULL,
    'bb275243-05d5-48af-8113-ee9536ac7429'
  ),
  (
    '8c24bea7-36ed-40d0-b3fe-50c23e7936ab',
    'contain-the-rumor-protect-the-people',
    'Contain the Rumor, Protect the People',
    'Independent professional publication',
    NULL,
    '2025',
    'A concise incident-governance analysis of responsible communications during an unverified cyber event, emphasizing evidence discipline, public guidance, regulatory coordination, investigative integrity, and threat-actor incentives.',
    NULL,
    'cybersecurity_grc',
    'draft',
    40,
    'four_minute_read',
    'host_pdf',
    NULL,
    'b31d3cc2-111f-4f0d-bd56-d19666c0dade'
  ),
  (
    '25628877-a099-42d1-8812-0e9c705bf62e',
    'data-breach-to-boardroom-cyber-governance',
    'From Data Breach to Boardroom: Why Cybersecurity Is Now Corporate Governance',
    'Independent professional publication',
    NULL,
    '2025',
    'A short professional analysis framing cybersecurity incidents as governance, resilience, accountability, regulatory, business-continuity, and trust issues rather than purely technical failures.',
    NULL,
    'cybersecurity_grc',
    'draft',
    50,
    'four_minute_read',
    'host_pdf',
    NULL,
    '1598966c-b991-4f31-8828-f9e2d4664bc6'
  ),
  (
    'ad297187-e3c6-4317-a72f-bc661632e226',
    'orb-to-oversight-world-app-privacy',
    'From Orb to Oversight: Why the NPC Paused World App',
    'Independent professional publication',
    NULL,
    '2025',
    'A privacy-governance analysis of biometric processing, consent, transparency, proportionality, irreversible identity risk, and regulatory oversight through the World App and Orb case in the Philippines.',
    NULL,
    'privacy_ai',
    'draft',
    60,
    'four_minute_read',
    'host_pdf',
    NULL,
    'ba78a7f8-834d-4e85-a63f-78de5c5af0a1'
  ),
  (
    'cd76c098-66b3-4a80-a621-35a0181ab18e',
    'you-are-easier-to-hack-than-everything',
    'You Are Easier to Hack Than Everything',
    'Independent professional publication',
    NULL,
    '2025',
    'An accessible cybersecurity piece examining social engineering, human-centered attack techniques, organizational awareness, verification controls, and practical defenses against manipulation-based intrusion.',
    NULL,
    'cybersecurity_grc',
    'draft',
    70,
    'four_minute_read',
    'host_pdf',
    NULL,
    '52e8ba31-0122-4a09-b09e-e5fb16d102f7'
  ),
  (
    'd018f779-c07d-4a85-945d-b644b3d3e33e',
    'before-blocks-build-the-bedrock',
    'Before Blocks, Build the Bedrock: Why Blockchain Shouldn''t Lead Philippine Budget Reform—Yet',
    'Independent professional publication',
    NULL,
    '2025',
    'An editorial arguing that public-sector digital reform should prioritize institutional capacity, interoperable and reliable data, security controls, auditability, and workforce readiness before adopting blockchain as a trust mechanism.',
    NULL,
    'cybersecurity_grc',
    'draft',
    80,
    'editorial',
    'host_pdf',
    NULL,
    '9980ca4b-c0ff-45b9-bfb3-283ffdedcf7d'
  ),
  (
    '5cb691fd-d699-48cc-867d-ac20c77d8845',
    'price-of-ubiquity-gcash-critical-infrastructure',
    'The Price of Ubiquity: GCash Is Now Critical Infrastructure',
    'Independent professional publication',
    NULL,
    '2025',
    'A contemporaneous cybersecurity and public-trust analysis of the risk created when a widely used digital-payment platform becomes socially and economically critical infrastructure.',
    NULL,
    'cybersecurity_grc',
    'draft',
    90,
    'four_minute_read',
    'host_pdf',
    NULL,
    '880703b6-29cb-440a-b60e-8568a76b0a71'
  ),
  (
    '0133a00f-c307-4135-8bdb-48018bb9161d',
    'philippine-elections-2025-data-privacy',
    'Philippine Elections 2025: The Alarming Rise of Unsecured Personal Data Processing',
    'Independent professional publication',
    NULL,
    '2025',
    'An editorial on privacy risk in election-period and public-assistance data processing, focusing on identification data, public disclosure, health information, proportionality, data minimization, and citizen awareness.',
    NULL,
    'privacy_ai',
    'draft',
    100,
    'editorial',
    'host_pdf',
    NULL,
    '8af86f88-8595-4812-8177-47ca30778300'
  );
